version: '3.8'

services:
  signaling-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: network-master-signaling
    ports:
      - "8080:8080"
    environment:
      - SIGNALING_ADDR=:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - signaling-network

networks:
  signaling-network:
    driver: bridge 